name: 'Auto Assign'
on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto Assign Action'
        uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          addReviewers: true
          addAssignees: author
          reviewers:
            - Safnaj
          numberOfReviewers: 1 
